# Generated by Django 4.2.3 on 2024-04-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addItems',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('item_image', models.ImageField(upload_to='media/')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('dis', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'additems',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Ecommerce_app_cart',
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('opid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
                ('role', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pay_mode', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_app.additems')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
