# Generated by Django 4.2.3 on 2024-04-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='mid',
        ),
        migrations.AddField(
            model_name='cart',
            name='iid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_app.additems'),
            preserve_default=False,
        ),
    ]
