# Generated by Django 4.2.3 on 2024-04-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0002_remove_cart_mid_cart_iid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlinepayment',
            table='Online_Payment',
        ),
    ]
