# Generated by Django 4.2.3 on 2024-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0005_delete_onlinepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('opid', models.AutoField(primary_key=True, serialize=False)),
                ('iid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('gtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'Online_Payment',
            },
        ),
    ]
